[features]
seeds = false
[programs.devnet]
inooo_staking = "BL3gV368of9wpkyG4p5LkpoNK6QaxhuxxV3CYzqrW6T"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/guardian/inooo-staking/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
